[package]
name = "gpui_platform"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/gpui_platform.rs"

[features]
default = []
bench-support = ["gpui/bench-support", "gpui_macos/bench-support"]
font-kit = ["gpui_macos/font-kit"]
test-support = ["gpui/test-support", "gpui_macos/test-support", "gpui_windows/test-support"]
screen-capture = ["gpui/screen-capture", "gpui_macos/screen-capture", "gpui_windows/screen-capture", "gpui_linux/screen-capture"]
runtime_shaders = ["gpui_macos/runtime_shaders"]
wayland = ["gpui_linux/wayland"]
x11 = ["gpui_linux/x11"]

[dependencies]
accesskit.workspace = true
anyhow.workspace = true
bitflags.workspace = true
channel.workspace = true
chrono.workspace = true
collections.workspace = true
futures.workspace = true
gpui_shared_string.workspace = true
gpui_types.workspace = true
gpui_util.workspace = true
http_client.workspace = true
image.workspace = true
journal.workspace = true
log.workspace = true
menu.workspace = true
parking_lot.workspace = true
rand.workspace = true
scap.workspace = true
scheduler.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
slotmap.workspace = true
smallvec.workspace = true
strum.workspace = true
task.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true
gpui.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
gpui_macos.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
gpui_windows.workspace = true
gpui = { workspace = true, features = ["windows-manifest"] }

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
gpui_linux.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
gpui_web.workspace = true
console_error_panic_hook.workspace = true
